export const FEATURE_DEFINITIONS: Record<string, string> = {
  "agenesisofcorpuscallosum": "A congenital condition where the corpus callosum (the structure connecting the two cerebral hemispheres) is partially or completely absent.",
  "airwayobstruction": "Partial or complete blockage of the airway that impairs airflow to the lungs.",
  "anxiety": "A psychological state characterized by excessive fear, worry, and physiological arousal.",
  "aplasiahypoplasiaoftmj": "Aplasia: Complete absence of temporomandibular joint\nHypoplasia: Underdevelopment of the joint",
  "archedeyebrows": "Eyebrows with a highly curved or elevated contour, often seen in syndromic conditions.",
  "arterialaneurysms": "Abnormal localized dilation of an artery due to weakening of the vessel wall.",
  "aspiration": "Entry of food, liquid, or saliva into the airway below the vocal folds.",
  "asymmetricshortfingers": "Unequal shortening of fingers on one or both hands due to skeletal developmental anomalies.",
  "atrialseptaldefectasd": "A congenital heart defect characterized by an opening in the atrial septum, allowing blood flow between atria.",
  "beakednose": "A nose with a prominent, curved bridge resembling a beak.",
  "behavioralissues": "Patterns of behavior that are socially inappropriate, disruptive, or maladaptive.",
  "bifiduvula": "A split or cleft uvula, often indicating submucous cleft palate.",
  "bipolardisorder": "A mood disorder with episodes of mania/hypomania and depression.",
  "brainanomalies": "Structural abnormalities in the brain due to abnormal development or injury.",
  "broadthumbs": "Thumbs that are wider than normal due to skeletal variation.",
  "cardiacdefects": "Structural abnormalities of the heart present at birth (congenital heart disease).",
  "catlikecry": "A high-pitched, monotonic cry resembling a cat, classically seen in Cri-du-chat syndrome.",
  "cervicalspineanomalies": "Structural abnormalities of the neck vertebrae.",
  "clinodactyly": "Curvature of a finger, typically the fifth digit, in the radial or ulnar direction.",
  "clubfoot": "A congenital deformity where the foot is twisted inward and downward.",
  "coarsefacialfeatures": "Thickened or heavy facial appearance due to soft tissue or skeletal changes.",
  "coloboma": "A congenital defect resulting in missing tissue in structures of the eye or eyelid.",
  "conductivehearingloss": "Hearing loss due to impaired transmission of sound through outer or middle ear.",
  "conotruncaldefect": "A group of heart defects involving outflow tracts of the heart (e.g., Tetralogy of Fallot).",
  "coronalcraniosynostosis": "Premature fusion of the coronal suture of the skull, leading to abnormal head shape.",
  "craniosynostosis": "Premature fusion of one or more cranial sutures, leading to abnormal skull growth and shape.",
  "cryptorchidism": "Failure of one or both testes to descend into the scrotum.",
  "decreasedenamel": "Reduced thickness or quality of tooth enamel, making teeth prone to decay.",
  "depressednasaltip": "A nasal tip that appears flattened or positioned lower than normal.",
  "developmentaldelay": "Slower-than-expected achievement of motor, cognitive, language, or social milestones.",
  "distractibility": "Reduced ability to maintain attention, with easy diversion by external stimuli.",
  "downwardslantingpalpebralfissures": "The outer corners of the eyes are positioned lower than the inner corners.",
  "droopingeyelidsptosis": "Abnormal drooping of the upper eyelid due to muscle or nerve dysfunction.",
  "dysmorphicfacialfeatures": "Facial characteristics that deviate from typical morphology, often indicating genetic conditions.",
  "earanomalies": "Structural abnormalities of the external, middle, or inner ear.",
  "encephalocele": "Neural tube defect where brain tissue protrudes through a skull defect.",
  "endocrineabnormalities": "Disorders involving hormone production or regulation.",
  "epibulbarlipodermoids": "Benign growths of fatty tissue on the surface of the eye (conjunctiva).",
  "epicanthalfolds": "Skin folds covering the inner corner (medial canthus) of the eyes.",
  "exophthalmos": "Abnormal protrusion of the eyeballs from the orbit.",
  "facialasymmetry": "Unequal size, shape, or position of facial structures on either side.",
  "feedingdifficulty": "Impairment in the ability to suck, chew, or swallow effectively.",
  "flatface": "Reduced forward projection of facial structures, especially midface region.",
  "flatfacialprofile": "Lack of normal convexity when viewed from the side due to midface retrusion.",
  "flatnasalbridge": "Reduced height of the nasal bridge, giving a flattened appearance.",
  "flatphiltrum": "Absence or reduction of the vertical groove between nose and upper lip.",
  "frequentmiddleearanomalies": "Recurrent or structural abnormalities affecting the middle ear system.",
  "genitalanomalies": "Structural abnormalities of the external or internal genital organs.",
  "glossoptosis": "Downward and posterior displacement of the tongue, often causing airway obstruction.",
  "growthretardation": "Slower-than-normal physical growth resulting in below-average height/weight for age.",
  "hearinglossconductivesensorineuralhighfrequency": "Partial or complete inability to hear due to:\nConductive: outer/middle ear issues\nSensorineural: inner ear/auditory nerve damage\nHigh-frequency: loss in higher pitch perception",
  "hemihypertrophy": "Asymmetric overgrowth of one side of the body or a body part.",
  "holoprosencephaly": "A developmental brain disorder where the forebrain fails to divide into two hemispheres.",
  "hoodedeyes": "Excess skin folds over the upper eyelids, partially covering them.",
  "hyperactivity": "Excessive motor activity such as restlessness, fidgeting, or inability to stay still.",
  "hypernasality": "Excessive nasal resonance during speech due to velopharyngeal insufficiency.",
  "hypertelorism": "Increased distance between two body parts, typically the eyes (orbital spacing).",
  "hypocalcemia": "Abnormally low levels of calcium in the blood.",
  "hypoplasiamalarmaxillarymandibularmidface": "Underdevelopment or incomplete development of facial bones or structures.",
  "hypotonia": "Decreased muscle tone resulting in floppiness and reduced resistance to movement.",
  "hypospadias": "A congenital condition where the urethral opening is located on the underside of the penis.",
  "immunedeficiency": "Impaired function of the immune system, leading to increased susceptibility to infections.",
  "intellectualdisability": "Significant limitations in intellectual functioning and adaptive behavior, with onset during developmental period.",
  "jointhypermobility": "Increased range of motion in joints beyond normal limits due to ligament laxity.",
  "languagedelaydisorder": "Delayed or impaired development of language comprehension and/or expression.",
  "learningdisability": "A neurodevelopmental disorder affecting academic skills like reading, writing, or math.",
  "limbanomalies": "Structural abnormalities of the arms or legs due to developmental defects.",
  "longface": "Increased vertical facial dimension, often due to maxillary excess or mandibular growth patterns.",
  "longlimbs": "Disproportionately elongated arms and legs relative to body size.",
  "macrostomia": "An abnormally large mouth opening due to lateral extension of oral fissure.",
  "macroglossia": "Enlargement of the tongue beyond normal size.",
  "malarhypoplasia": "Underdevelopment of the cheekbones (zygoma).",
  "mandibularhypoplasia": "Underdevelopment of the lower jaw (mandible).",
  "microcephaly": "Abnormally small head circumference due to reduced brain growth.",
  "micrognathia": "Abnormally small lower jaw, often causing feeding and airway issues.",
  "micropenis": "An abnormally small penis with normal structure, typically due to hormonal deficiency.",
  "microphthalmia": "Abnormally small eyes due to incomplete ocular development.",
  "microtia": "Congenital underdevelopment or absence of the external ear (pinna).",
  "mildpsychosocialissues": "Minor difficulties in social interaction, emotional regulation, or behavior.",
  "missingteeth": "Congenital absence of one or more teeth (hypodontia).",
  "mittenlikesyndactyly": "Fusion of fingers giving a \"mitten-like\" appearance, commonly seen in syndromic conditions.",
  "narrowpalpebralfissures": "Reduced horizontal width of the eye openings.",
  "narrowpalate": "Reduced width of the palatal arch, affecting oral cavity space.",
  "neonatalhypoglycemia": "Low blood glucose levels in newborns, which can affect brain function.",
  "neonatalteeth": "Teeth present at birth or within the first month of life.",
  "oralapraxia": "Motor planning disorder affecting voluntary oral movements without muscle weakness.",
  "osteoarthritis": "Degenerative joint disease characterized by cartilage breakdown and joint pain.",
  "overgrowthprenatalpostnatal": "Excessive growth occurring before or after birth, often syndromic.",
  "pneumonia": "Infection of the lungs causing inflammation of alveoli and impaired gas exchange.",
  "polycystickidneys": "Presence of multiple fluid-filled cysts in the kidneys, affecting function.",
  "polydactyly": "Presence of extra fingers or toes.",
  "poorgrowthdwarfism": "Significantly reduced growth resulting in short stature below normal range.",
  "preauricularpits": "Small congenital indentations near the external ear.",
  "prognathia": "Forward protrusion of the jaw (usually mandible).",
  "proptosis": "Forward displacement or bulging of the eye.",
  "renalanomalies": "Structural or functional abnormalities of the kidneys.",
  "respiratoryissues": "Problems affecting breathing or lung function.",
  "retinaldetachment": "Separation of the retina from underlying tissue, leading to vision loss.",
  "schizophrenia": "A psychiatric disorder with distorted thinking, perception, and behavior.",
  "seizures": "Sudden abnormal electrical activity in the brain causing involuntary movements or altered consciousness.",
  "shortnose": "Reduced length of the nasal structure.",
  "shortpalpebralfissures": "Decreased horizontal eye opening length.",
  "shortstature": "Height significantly below average for age and sex.",
  "skeletalanomalies": "Structural abnormalities of bones and skeletal system.",
  "skinhyperextensibility": "Increased ability of skin to stretch beyond normal limits.",
  "smallears": "Reduced size of the external ear (microtia-related or isolated).",
  "socialpsychologicalimpact": "Effects of a condition on social interaction, self-esteem, and mental health.",
  "speechandlanguagedelay": "Delay in development of speech production and/or language skills.",
  "strabismus": "Misalignment of the eyes where they do not look in the same direction.",
  "swallowingdifficultydysphagia": "Impairment in the ability to safely and efficiently swallow.",
  "syndactyly": "Fusion of two or more fingers or toes.",
  "thinupperlip": "Reduced vertical height of the upper lip vermilion.",
  "tongueabnormalitieslobulationnotch": "Structural irregularities in the shape or surface of the tongue.",
  "trachealanomalies": "Structural abnormalities of the trachea affecting airway function.",
  "umbilicalhernia": "Protrusion of abdominal contents through the umbilical opening.",
  "upperairwaystenosis": "Narrowing of the upper airway, causing breathing difficulty.",
  "ventricularseptaldefectvsd": "An opening in the ventricular septum, allowing blood flow between ventricles.",
  "vertebraldefects": "Abnormalities in the structure or formation of vertebrae.",
  "verticalmaxillaryexcess": "Excessive vertical growth of the upper jaw, leading to long face appearance.",
  "visualimpairment": "Reduced ability to see that cannot be corrected fully with lenses.",
  "webbing": "Presence of skin folds between body parts, commonly fingers or neck."
};
